# Generated by Django 2.0.2 on 2018-03-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artical_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='pub_time',
            field=models.DateTimeField(null=True),
        ),
    ]
